 source 'https://rubygems.org'
ruby '2.3.5'

gem 'devise'
gem 'figaro'
gem 'jbuilder', '~> 2.0'
gem 'pg'
gem 'puma'
gem 'rails', '5.1.4'
gem 'redis'
gem 'omniauth-facebook'
gem 'uuidtools'

gem 'country_select'
gem 'cloudinary', '1.1.7'
gem 'attachinary', github: 'assembler/attachinary'
gem 'jquery-fileupload-rails'
gem 'coffee-rails'
gem 'pundit'
gem 'facebookads'
gem 'postmark-rails'

gem 'autoprefixer-rails'
gem 'bootstrap-sass'
gem 'font-awesome-sass'
gem 'sass-rails'
gem 'jquery-rails'
gem 'simple_form'
gem 'uglifier'
gem 'webpacker'

group :development, :test do
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'letter_opener'
end
